### ISSUE TITLE
css ID identifiers are not linked properly from sourcegraph symbol results

### ISSUE THREAD

**Issue by rothfels** [sourcegraph/srclib-css#3]
See video for example: http://cl.ly/0u1S2m2R0t32

**Comment by rothfels** [comment]
It looks like they are missing URL encoding, e.g. `/def/Dir/testrepo/-/%23container` vs `/def/Dir/testrepo/-/#container`

**Comment by rothfels** [comment]
@beyang is this something that should be done on the Sourcegraph side?

**Comment by beyang** [comment]
Yes the UI should handle that. Relevant code is in the react frontend I think

**Comment by chris-ramon** [comment]
closing this one, addressed on: https://github.com/sourcegraph/sourcegraph/pull/1906/commits/499dae00d77947605fc20c3cdba938800a5ffd85
